---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgANMulhfi7BWqI/XcWql/Ln1gmoUlQpP51BauxWKuK9ZitDVL8ntlp4oaWsIPiyFSYvJWtqlxAjR9SrLgInCz0dagcoUnDfDmQl+22n2T3bUUP7sWpdfk7hHm9ps0YOSbwBFmJPyXo9QZzrAJ/mgBq6fqKYds/JUwC9kdvGbJvOxhHMPC6ZDeqC1W4uEhyiRBhGofhyv3xopKyjDBKk2jtdlhKbQbJgwDMG1B/QHF9LtcgbgG3wkx+FRYytkmFNQwXqz8WmkZibFHazUpYuWSOqbtLdQkdXjzJ40maVOzHimbGPwI4M/099X9PmT4psMFSV5/j28BbIdUP1r0KC3OU8yyV6d/JEWZspD5XVrL1Sw3MPL3qyqtEdwL9oiRi7ORbhs2sE6HObzyWec4ccop2YNQWKslFvdX8Y2baUzt2ZAFGPsiXwfr1MNzDAhPMLQW4yqqu3o9LIbOgDIjm5+vzJW9vAoWj+BmsDqsV9RliP47EFYnZ3h8/+BXwJBenrwYjCjBd6tqkD2h4fyL8IaOlaJojuzl+HCXnFJitmgls47gKaOWu/PQNh1fiPGVCn6V0bGMnehCJi7dz6w/au6irXu1/So1VjyMn/l9F/KVUXebNgBqx6AttbkO1AFWVREDkKuVsyrOrmIvfflmRvNEPnZJd1hgW9n5NvZkEulRfpmEaa3nqE7wg1OT73TSrArNzH8+CgypYHWGisKRgfBdEYfZIzdA==
  template:
    metadata:
      labels:
        app: postgresql
      name: postgres-secret
      namespace: postgres
    type: Opaque
