---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCpofJH8oss3k474qFKiigL5OmaSIFEJ2ZpoXHpazgteYaipycVPyoJKqWrNb3A7eKhZNgb2vH72BgYsad59aTSRhZM9aYC0KYKeEWisuERb7Wee4MUIECRMSsBqsspQV8GmjeK4RYlyC2CGBuQwSOV+If6aKlCLzeJfxDvIyb2dy2X388rPa7qYALR+u4Ar2bUP+VxwLD9MbiiAGpx2go5EumTTJHa6Y+V0Fzc58gMazZABWfos8Cg63yf5o5HF97hkcGbB7+aD9tS9Rf2nEq2HXbJYGsGRwR9lm5MpDmI1iKeNYZOzEIjJ5Vd13qGrXENJEkCrGdA4i0iHlh4aftnHZfXZvMxPIPLmAPyLOnifUnIkMApqp38Y/R1B9ov/YyghP5fzqjM01kPJ4ESkbD4eIwLzLMVHP15VcbfrrpuQ5/g0ENmDEjoBE3qUPtk3F+M5iuH2+lYK0J7p0AO1N8rDoh2c7UaygXAqHKAozUb1KKXfCxFW+3l3TMgHRrdAJqLgpa5rKtPF1A+BZV0trKTcGBeq0OIpPEBgt/pGcjYbjg5FqQO4/u/D2BsBgVSD/H+wYlMEOs7QO00hi4kC4Vgus0TuclnJ9foR1QbA8SNCxcQNAs309Gk84VrPj1u/3ac3lSWCYXsXSVbnEu8KbYhq1yDoBy6xdVP23P496+lvPkWpwsC8HR9QpVRDLtR5Fcy1GfLkZXeXnsYVOC+TUIK
  template:
    metadata:
      labels:
        app: postgresql
      name: postgres-secret
      namespace: postgres
    type: Opaque
